configure.ac: Add some more warnings for --enable-warnings=fatal.
Not using -Wshadow because that breaks the build:
matrix.cc:28:80: error: declaration of 'y0' shadows a member of 'this' [-Werror=shadow]
 Matrix::Matrix(double xx, double yx, double xy, double yy, double x0, double y0)